config/routes.rb
Rails.application.routes.draw do

  get 'listings/new'

  get 'listings/create'

  get 'listings/edit'

  get 'listings/update'

  get 'listings/show'

  get 'listings/index'

  get 'listings/delete'

  get 'companies/new'

  get 'companies/create'

  get 'companies/edit'

  get 'companies/update'

  get 'companies/index'

  get 'companies/show'

  get 'companies/delete'

  get 'home/index'

  root to: 'home#index'
  devise_for :users

end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/listing.rb
class Listing < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :confirmable, :rememberable, :trackable, 
         :validatable, :lockable, :recoverable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def index
  end

  def show
  end

  def delete
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  	if user_signed_in?
  		render 'home'
  	else
  		render 'front'
  	end
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def show
  end

  def index
  end

  def delete
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis
  def full_title(page_title)
    base_title = "Angelstrap"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

  # Used to style flash messages based on their type
  def flash_class(level)
    p level
    case level
      when "notice" then "alert alert-info"
      when "alert" then "alert alert-info"
      when "success" then "alert alert-success"
      when "error" then "alert alert-danger"
      when "danger" then "alert alert-danger"
    end
  end

  def sex_icon(sex)
    case sex
      when "Male" then "fa fa-male"
      when "Female" then "fa fa-female"
    end
  end

  def is_active?(controller, section)
    if current_page?(controller: controller, section: section)
      "active"
    else
      ""
    end
  end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/companies/create.html.slim
h1 Companies#create
p Find me in app/views/companies/create.html.slim

app/views/companies/delete.html.slim
h1 Companies#delete
p Find me in app/views/companies/delete.html.slim

app/views/companies/edit.html.slim
h1 Companies#edit
p Find me in app/views/companies/edit.html.slim

app/views/companies/index.html.slim
h1 Companies#index
p Find me in app/views/companies/index.html.slim

app/views/companies/new.html.slim
div.container

  h1 Startup Registration Form

app/views/companies/show.html.slim
h1 Companies#show
p Find me in app/views/companies/show.html.slim

app/views/companies/update.html.slim
h1 Companies#update
p Find me in app/views/companies/update.html.slim

app/views/home/front.html.slim
provide :title, 'Welcome'

div.jumbotron
  div.hero-unit
	  div.container
	    h1 Help garage-stage startups
	    h1 take off
	    br
	    a.btn.btn-lg.btn-primary href="#{new_user_registration_path}" Create Account

hr.half-rule

h3.centertext Startup founders have a tough job.

div.container
  div class="row centertext"
    div class="col-sm-4"
      h2
        span class="fa fa-smile-o fa-3x"
      p Ease their burden by investing in their tools and digital infrastructure.

    div class="col-sm-4"
      h2 
        span class="fa fa-thumbs-up fa-3x"
      p Win goodies and get first dibs on their products and services.

    div class="col-sm-4"
      h2 
        span class="fa fa-check-square-o fa-3x"
      p Quick, easy, and safe.

hr.half-rule

h3.centertext How does it work?

div.container.how-does-it-work
  div.row
    div.col-sm-offset-1.col-sm-5
      div.step-by-step
        div.step
          div.stepnumber 1
          div.stepdescription Founders create listings that describe their needs
        div.step
          div.stepnumber 2
          div.stepdescription Angels pay for those services through Angelstrap
        div.step
          div.stepnumber 3
          div.stepdescription Angelstrap signs up for the services on the founders' behalf
    div.col-sm-offset-1.col-sm-5.picture.centertext
      p Pictures

hr.half-rule

h3.centertext Interested?
h4.centertext We haven't launched yet, but we can let you know when we do.

div.container.subscribe
  div.row
    div.col-sm-5.col-sm-offset-1.form
      div id="mc_embed_signup"
        <form action="//angelstrap.us11.list-manage.com/subscribe/post?u=a6d951be52ca9178407f4b2aa&amp;id=951c0a650e" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
        .form-group
          br
          h4 Subscribe to our mailing list
          .input-group
            span.input-group-addon
              i class="fa fa-envelope"
            input.form-control placeholder="Email address" name="EMAIL"
          

          div style="position: absolute; left: -5000px;"
            input type="text" name="b_a6d951be52ca9178407f4b2aa_951c0a650e" tabindex="-1" value=""
        .form-group
          input.button.btn.btn-primary type="submit" value="Subscribe" name="subscribe"
    div.col-sm-5.number-of-subscribers.centertext
      h3 Number of Subscribers
      h3.number 132
    div.col-sm-1

app/views/home/home.html.slim
provide :title, 'Home'

div.container
  h1 Home Page
  p This is the home page where people can register their companies and create listings.
  br
  a.btn.btn-lg.btn-primary href="#{companies_new_path}" Register Startup

  a.btn.btn-lg.btn-primary href="#{listings_new_path}" Create Listing

  h3 Popular Listings
  div.row
    div.col-sm-4.centertext.listing-thumb Listing 1
    div.col-sm-4.centertext.listing-thumb Listing 2
    div.col-sm-4.centertext.listing-thumb Listing 3
  div.row
    div.col-sm-4.centertext.listing-thumb Listing 4
    div.col-sm-4.centertext.listing-thumb Listing 5
    div.col-sm-4.centertext.listing-thumb Listing 6

app/views/home/index.html.slim
provide :title, 'Home'

div.jumbotron
  div.hero-unit
	  div.container
	    h1 Help early-stage startups
	    h1 take off
	    br
	    a.btn.btn-lg.btn-primary Create Account

hr.half-rule

div.container
  div class="section-title-black"
    div class="row centertext"
      div class="col-sm-4"
	      h2
	        span class="fa fa-smile-o fa-3x"
	      p Ease their burden by investing in their tools and digital infrastructure.

      div class="col-sm-4"
        h2 
          span class="fa fa-thumbs-up fa-3x"
        p Win goodies and get first dibs on their products and services.

      div class="col-sm-4"
        h2 
          span class="fa fa-check-square-o fa-3x"
        p Quick, easy, and safe.

hr.half-rule

app/views/layouts/_footer.html.slim
footer class="footer"
  div class="container centertext"
    p Copyright &copy; 2015 Agile Online Ventures

app/views/layouts/_header.html.slim
header

  div class="navbar navbar-inverse"
    .container
      button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"
        span class="icon-bar"
        span class="icon-bar"
        span class="icon-bar"
      a.navbar-brand href="#{root_url}" Angelstrap

      div class="collapse navbar-collapse"
        ul class="nav navbar-nav navbar-right"
          li
            = link_to root_path do
                i class="fa fa-home fa-lg"
          - if !signed_in?
            li
              = link_to 'Sign Up', new_user_registration_path
            li
              = link_to 'Sign In', new_user_session_path
          - else
            li
              a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"
                i class="fa fa-user fa-lg"
                  span.caret
              ul.dropdown-menu role="menu"
                li
                  = link_to 'Account', edit_user_registration_path
                li.divider
                li
                  = link_to 'Sign out', destroy_user_session_path, method: "delete"

app/views/layouts/_shim.html.slim
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk.html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag %>
    <%= render 'layouts/shim' %>
  </head>

  <body>

  	<%= render 'layouts/header' %>
  		
    <div class="centertext col-md-8 col-md-offset-2">
      <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %> alert-dismissable" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button> 
          <%= value %>
        </div>
      <% end %>
    </div>

  	<%= yield %>

  	<%= render 'layouts/footer' %>

  	<%= debug(params) if Rails.env.development? %>

  </body>
  
</html>

app/views/listings/create.html.slim
h1 Listings#create
p Find me in app/views/listings/create.html.slim

app/views/listings/delete.html.slim
h1 Listings#delete
p Find me in app/views/listings/delete.html.slim

app/views/listings/edit.html.slim
h1 Listings#edit
p Find me in app/views/listings/edit.html.slim

app/views/listings/index.html.slim
h1 Listings#index
p Find me in app/views/listings/index.html.slim

app/views/listings/new.html.slim
div.container

  h1 New Listing Form

app/views/listings/show.html.slim
h1 Listings#show
p Find me in app/views/listings/show.html.slim

app/views/listings/update.html.slim
h1 Listings#update
p Find me in app/views/listings/update.html.slim